In [ ]:
#Calculate Standard Deviation of an array
def calculateStandardDeviation(array):
    n = len(array)
    mean = sum(arr)/n

    sumResidualsSquared = 0
    for num in arr:
        sumResidualsSquared += (float(num)-mean)**2

    stdDev = math.sqrt(sumResidualsSquared/n)
    return stdDev

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import math
contents = []
while True:
    try:
        line = input()
    except EOFError:
        break
    contents.append(line)


n = int(contents[0])

arr = [int(num) for num in contents[1].split(" ")]

In [ ]:
#Get median of an array
#Get median index of an array:
#   - will return whole number float index if odd n
#   - will return float (.5) index if even n
#Returns (medianIndex, median)
def getMedian(arr):
    n = len(arr)
    arr = sorted(arr)

    if(n%2==0): #even number of elements
        median = (arr[int(n/2)-1]+arr[int(n/2)])/2
    else:
        median = arr[int(n/2)]

    return (n/2,median)


#Get any desired quartile from an array
def getQuartile(arr,quartile):
    n = len(arr)
    arr = sorted(arr)

    medianInfo = getMedian(arr)
    medianIndex = medianInfo[0]
    medianVal = medianInfo[1]

    #print(medianInfo)

    if(quartile == 2):
        return median

    #Split array at median 
    if(medianVal%2==0):
        lowerArr = arr[:int(medianIndex)]
        higherArr = arr[int(medianIndex)+1:]
    else:
        lowerArr = arr[:int(medianIndex)+1]
        higherArr = arr[int(medianIndex)+1:]

    q1 = getMedian(lowerArr)[1]
    q3 = getMedian(higherArr)[1]

    if(quartile == 1):
        return q1

    if(quartile == 3):
        return q3

    return "Invalid quartile number provided"

In [ ]:
import math

#Calculates probability of no more than "successes" in the number of trials provided.
#For example, prob of no more than 2 successes in 6 trials would enter binomialCDF(2,6,p)
def binomialCDF(successes, trials, p):
    prob = 0

    for successNum in range(successes+1):
        combs = int((math.factorial(trials))/((math.factorial(successNum))*math.factorial(trials-successNum)))

        prob += combs*(p)**successNum*(1-p)**(trials - successNum)

    return prob

In [21]:
import numpy as np 

after = np.array([[1,3,7],[5,10,15],[12,18,25]])

before = np.zeros(shape = (3,3))

n = 3
m = 3

for x in range(n):
    for y in range(m):
        #print(before,"\n")
        beforeSum = before[:x+1,:y+1]
        #print(beforeSum,"\n")
        before[x][y] = after[x,y] - sum(map(sum, beforeSum))

print(before)


[[1. 2. 4.]
 [4. 3. 1.]
 [7. 1. 2.]]
